import type { LiveBlogView } from './types'

/**
 * NÄIDISANDMED otseblogi vahekaardi kujundamiseks. Kõik postitused on
 * väljamõeldud; fotod on saidi enda päris rallifotod (`public/images/`).
 * Asendatakse Sanity adapteriga, kui blogi läheb käiku — vahekaart ja
 * API-route jäävad samaks.
 */
export const LIVE_BLOG_FIXTURE: LiveBlogView = {
  eventId: 'ev-2026-05',
  eventName: 'Humus Paide Rally 2026',
  hashtags: ['EMV2026', 'PaideRally'],
  generatedAt: '2026-08-22T18:10:00+03:00',
  posts: [
    {
      id: 'lp-014',
      eventId: 'ev-2026-05',
      kind: 'notice',
      author: { name: 'Paide Rally korraldaja', handle: null, areaLabel: null, role: 'moderator' },
      body: 'Lõputseremoonia algab kell 18.30 Paide Keskväljakul. Autod saabuvad Pärnu tänava kaudu — hoidke tee vaba.',
      stageCode: null,
      image: null,
      video: null,
      embed: null,
      credit: null,
      pinned: true,
      publishedAt: '2026-08-22T17:52:00+03:00',
    },
    {
      id: 'lp-013',
      eventId: 'ev-2026-05',
      kind: 'photo',
      author: { name: 'Mari', handle: '@mari.rallifoto', areaLabel: 'SS10', role: 'trusted' },
      body: 'Viimane katse läbi. Volver / Sõna tulid finišisse ja publik plaksutas veel minuti.',
      stageCode: 'SS10',
      image: { src: '/images/action-crowd.jpg', width: 1600, height: 1067, alt: 'Pealtvaatajad rallisõiduki finišis' },
      video: null,
      embed: null,
      credit: null,
      pinned: false,
      publishedAt: '2026-08-22T17:31:00+03:00',
    },
    {
      id: 'lp-012',
      eventId: 'ev-2026-05',
      kind: 'embed',
      author: { name: 'Jaan', handle: null, areaLabel: 'Hooldus', role: 'moderator' },
      body: 'Paide Rally oma pilt teenindusalast.',
      stageCode: null,
      image: null,
      video: null,
      embed: { url: 'https://www.instagram.com/p/DAAAAAAAAAA/', provider: 'instagram', handle: '@paiderally' },
      credit: null,
      pinned: false,
      publishedAt: '2026-08-22T16:48:00+03:00',
    },
    {
      id: 'lp-011',
      eventId: 'ev-2026-05',
      kind: 'text',
      author: { name: 'SS9 pealtvaataja', handle: null, areaLabel: 'SS9', role: 'moderated' },
      body: 'Nr 14 seisab katse keskel, mõlemad meeskonnaliikmed on autost väljas ja terved. Katse jätkub.',
      stageCode: 'SS9',
      image: null,
      video: null,
      embed: null,
      credit: null,
      pinned: false,
      publishedAt: '2026-08-22T15:57:00+03:00',
    },
    {
      id: 'lp-010',
      eventId: 'ev-2026-05',
      kind: 'video',
      author: { name: 'Mari', handle: '@mari.rallifoto', areaLabel: 'SS8', role: 'trusted' },
      body: 'Kruusakurv SS8 lõpus — siin tuleb kõige rohkem külgu.',
      stageCode: 'SS8',
      image: null,
      video: { src: '/videos/placeholder.mp4', poster: '/images/action-speed.jpg' },
      embed: null,
      credit: null,
      pinned: false,
      publishedAt: '2026-08-22T15:12:00+03:00',
    },
    {
      id: 'lp-009',
      eventId: 'ev-2026-05',
      kind: 'photo',
      author: { name: 'Kati', handle: '@kati.kask', areaLabel: 'SS7', role: 'moderated' },
      body: 'Vihm tuli ja läks. Rada on nüüd libe nagu seep.',
      stageCode: 'SS7',
      image: { src: '/images/action-rain.jpg', width: 1600, height: 1067, alt: 'Rallisõiduk vihmases kiiruskatses' },
      video: null,
      embed: null,
      credit: 'Foto: Kati Kask',
      pinned: false,
      publishedAt: '2026-08-22T14:20:00+03:00',
    },
    {
      id: 'lp-008',
      eventId: 'ev-2026-05',
      kind: 'notice',
      author: { name: 'Paide Rally korraldaja', handle: null, areaLabel: null, role: 'moderator' },
      body: 'SS7 start lükkub 15 minutit edasi (13.45). Pealtvaatajaalad on avatud.',
      stageCode: 'SS7',
      image: null,
      video: null,
      embed: null,
      credit: null,
      pinned: false,
      publishedAt: '2026-08-22T13:21:00+03:00',
    },
    {
      id: 'lp-007',
      eventId: 'ev-2026-05',
      kind: 'embed',
      author: { name: 'Jaan', handle: null, areaLabel: 'Hooldus', role: 'moderator' },
      body: null,
      stageCode: null,
      image: null,
      video: null,
      embed: { url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ', provider: 'youtube', handle: null },
      credit: null,
      pinned: false,
      publishedAt: '2026-08-22T12:40:00+03:00',
    },
    {
      id: 'lp-006',
      eventId: 'ev-2026-05',
      kind: 'photo',
      author: { name: 'Mari', handle: '@mari.rallifoto', areaLabel: 'SS6', role: 'trusted' },
      body: 'SS6 — täisgaasiga läbi Roosna-Alliku küla. Publikut on murdu.',
      stageCode: 'SS6',
      image: { src: '/images/action-speed.jpg', width: 1600, height: 1067, alt: 'Rallisõiduk kiirel läbisõidul' },
      video: null,
      embed: null,
      credit: null,
      pinned: false,
      publishedAt: '2026-08-22T11:58:00+03:00',
    },
  ],
}
